---
services:
    - docker

before_install:
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
    - 'docker build -t "$DOCKER_USERNAME"/docker.spark-hs:2.0.0 .'
    - 'docker push "$DOCKER_USERNAME"/docker.spark-hs:2.0.0'
